version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: loan_management_db
    environment:
      POSTGRES_USER: loanuser
      POSTGRES_PASSWORD: loanpassword
      POSTGRES_DB: loan_management
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/

volumes:
  db_data: # Define the named volume